#!/usr/bin/env python3
import sys
import os
args = sys.argv
if args.__len__() < 3:
    print('{}:\n\tinput_file output_file'.format(os.path.basename(sys.argv[0])))
    sys.exit(1)
bin_file = args[1]
out_file = args[2]
if not os.path.exists(bin_file):
    print('no such file!')
    sys.exit(1)
with open(bin_file, 'rb')as fp:
    bin = fp.read()
with open(out_file, 'w')as fp:
    fp.write('char data[] = {')
    for b in bin:
        fp.write(hex(b).__str__() + ', ')
    fp.write('};')
